### ISSUE TITLE
Forward data to data199.com cloud

### ISSUE THREAD

**Issue by pkolmann** [sarnau/MMMMobileAlerts#10]
Thanks a lot for your project. I tried it and it works perfectly. Currently what I am missing is the possibility to still use the mobile app after starting the proxy.

Would it be possible to still forward the data to the cloud?

**Comment by sarnau** [comment]
Only if somebody writes a forwarder to the cloud. I don't like the Cloud for privacy reasons and use a mobile app with my local data (any home automation system with an iOS app will do)

**Comment by spipu** [comment]
i'm agree with you, it is very easy to get the value of any sensors of anybody... it is very dangerous.
I do not use the cloud anymore, and send all the values to my private server, associate to a webapp

**Comment by pkolmann** [comment]
I also believe in privacy and my own servers, but sometimes it might be a nice feature.

**Comment by sarnau** [comment]
Cool, thanks for the fast fix.
