### ISSUE TITLE
Doubts with the post request

### ISSUE THREAD

**Issue by oscargarciahernandez** [sarnau/MMMMobileAlerts#17]
Hi, I'm trying to get the full datasets doing post request using this code,
https://github.com/sarnau/MMMMobileAlerts/blob/master/MobileAlertsGatewayApplicationAPI.markdown

I've a few Doubts, 
Do i have to enter all my credential?, such as: phoneid, vendorid, version, build...

I've tried several configuration an i only get this error: 
u'{\r\n  "success": false,\r\n  "errorcode": 1051,\r\n  "errormessage": "The request parameters are are invalid",\r\n  "primarydomain": "www.data199.com"\r\n}'

and also a Runtime Error, An application error occurred on the server.

Thank you very much, regards, Oscar

**Comment by m4rky-m4rk** [comment]
Here is the code I have in my .sh file.

`curl -d deviceids=id1,id2,id3 -d phoneid=xxxxxx https://www.data199.com/api/pv1/device/lastmeasurement`

I use it with Openhab Exec binding to save the output. I then use regex to extract the data I want for charting with grafana and influx db. Works great.

**Comment by oscargarciahernandez** [comment]
thanks¡¡ 

i was trying to download all the data using the code of the IOS app, but i will use your method¡

**Comment by sarnau** [comment]
I just tried it and it seems to work.
