### ISSUE TITLE
MQTT Support for Arduino Sketch?

### ISSUE THREAD

**Issue by sboldt1978** [sarnau/MMMMobileAlerts#18]
Hi, it would be great if the Arduino Code would also have MQTT support. Furthermore it would be great if It would also run on an esp8266. With this cheap micro controller you don't even need a LAN connection, because it has Wifi onboard. :-)

regards,
Stephan

**Comment by sarnau** [comment]
I prefer wired connections via wireless – always more stable. But you probably could port it to the ESP32 etc.
