### ISSUE TITLE
Does the MA REST API work?

### ISSUE THREAD

**Issue by hfrmobile** [sarnau/MMMMobileAlerts#21]
Using REST-API-Tester: https://reqbin.com/

Sample from REST API documentation:
https://www.data199.com/api/pv1/device/lastmeasurement?deviceids=0B06A01157E4&phoneid=880071013613

Doing a POST as described in the documentation but always getting:
`{
    "Message": "Request parameters invalid"
}`

Asked MA (mobile alerts) support but they say that they won't give any support for the REST API.

This confuses me since the REST API is very, very limited (just supporting a few sensor types) + only supporting query the last value + only a few requests are allowed (no caching, using the REST API the developer has to care about it ....)

Can you put mit into the right direction? What I am missing here? The MA REST API doc claims "ID01, ID08, ID09, ID0B and ID0E sensors" are supported but do I have to provide that "sensor type id" somewhere? The above sample uses a "wind sensor" which should be supported ...

In my point of view using https://measurements.mobile-alerts.eu/ and parsing/converting to XML/JSON I will get much more information than using the "REST API" ....

e.g. https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid=880071013613

But before starting development I'd like to ask if such stuff maybe is already implemented by someone of you?

Looking forward hearing/reading from you.
--hfrmobile

**Comment by sarnau** [comment]
All the information I've found out is in this repository. The REST API I've never used, because I only use the sensors locally without their cloud.

**Comment by m4rky-m4rk** [comment]
REST API works. I am using it with Openhab opensource home automation platform.

Basically I have a script with this in it:

`curl -d deviceids=<yourdevice ID's> -d phoneid=<your phone ID> https://www.data199.com/api/pv1/device/lastmeasurement`

If you want see more details of this method or web page caching you can find more here:
https://community.openhab.org/t/mobile-alerts-and-openhab-2/21444. I posted this in my other issue here

**Comment by ElHoni** [comment]
did everyone tried to get battery level?

**Comment by sarnau** [comment]
There is no "level" per-se, but rather a "battery empty" warning. It's one bit.

**Comment by ElHoni** [comment]
i´ve added it to openhab and I use Javascript transformation to get the infos. But I don´t know if this works with battery level

**Comment by CestLaGalere** [comment]
@sarnau  you mention 
> The REST API I've never used, because I only use the sensors locally without their cloud.
I'm interested in how you can get the data locally - do you have a radio sniffer to receive the broadcast packets or get the data from the (ethernet connected) receiver? 
I had a look at the raw data in the packets sent but it was a greater effort than I was prepared to invest in decoding them and couldn't find further documentation. Thanks.

**Comment by sarnau** [comment]
I looked at the TCP/IP packages from the gateway. I have radio sniffers, but never went down that rabbit hole to analyze them (the 868MHz band is pretty crowded here and I didn't want to build a faraday cage just for this). Also: the gateway is cheap and easily available.
