### ISSUE TITLE
Gateway Application API Example error 1051

### ISSUE THREAD

**Issue by mguillem** [sarnau/MMMMobileAlerts#27]
Sadly trying the example at https://github.com/sarnau/MMMMobileAlerts/blob/master/MobileAlertsGatewayApplicationAPI.markdown for a MA10100 device fails with following answer:
```
{
  "success": false,
  "errorcode": 1051,
  "errormessage": "The request parameters are are invalid",
  "primarydomain": "www.data199.com",
  "result": {
    "total": 0
  }
}
```

Any idea?

**Comment by m4rky-m4rk** [comment]
API request only works for pro device versions and a few others. Don't think MA10100 is one of the pro sensors. For non pro I scrape the data from the sensor webpage

**Comment by monojk** [comment]
I also don't have success (printed the request string in the python script from https://sarnau.info/mobile-alerts-sensors/):
```
devicetoken=empty&vendorid=1FB220C4-CC15-4195-97CF-8BE4FD3DAE72&phoneid=Unknown&version=1.21&build=248&executable=Mobile Alerts&bundle=de.synertronixx.remotemonitor&lang=en&timezoneoffset=60&timeampm=true&usecelsius=true&usemm=true&speedunit=0&timestamp=1619346552&requesttoken=5fd4716dabdf9af077cdc636778bd3db&deviceids=0836C6E3AF5E
#1051 The request parameters are are invalid
```
whereas with the same deviceid:
```
curl -d deviceids=0836C6E3AF5E https://www.data199.com/api/pv1/device/lastmeasurement
{
  "devices": [
    {
      "deviceid": "0836C6E3AF5E",
      "lastseen": 1619349600,
      "lowbattery": false,
      "measurement": {
        "idx": 455669,
        "ts": 1619209328,
        "c": 1619209329,
        "sc": true,
        "t1": 6.9,
        "r": 60.372,
        "rf": 234,
        "rr": 0.0
      }
    }
  ],
  "success": true

```
What can be wrong?

**Comment by sarnau** [comment]
It is very well possible, that they changed their server based APIs. That's why I used my own gateway and never forwarded the packages to their server.

**Comment by SilverRoll** [comment]
I believe that my recent pull request #30 has fixed this.
