### ISSUE TITLE
Multiple Gateways

### ISSUE THREAD

**Issue by show2go** [sarnau/MMMMobileAlerts#29]
Hi!
I have two gateways on my network, but maserver seems to use only one of them. Is there a way to make both of them work?
Thanks!

**Comment by chik81** [comment]
I have two Gateways too and my maserver has no Problems with this. It is
only a Proxy also it is no relevant who use it.

Christian

show2go <notifications@github.com> schrieb am So., 7. Feb. 2021, 17:18:

**Comment by m4rky-m4rk** [comment]
In the phone app go to settings and you can find, add and configure gateways. I had two running once before.

**Comment by chik81** [comment]
Yes you must configure the Proxy in every gateway

Mark <notifications@github.com> schrieb am So., 7. Feb. 2021, 18:14:

**Comment by show2go** [comment]
Hey Guys,
thanks for the fast reply!!!
Done and running :)
One more question, how is your experience when the synology is offline? Will the gateways send the data to the origin server?
I tested to stop the service/programm, and they didnt sent the data to the mobilealert server.
i guess, the service is running stable?!
Thanks J
