### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by sarnau** [sarnau/MMMMobileAlerts#3]
It is completely unknown how the battery status is reported. I couldn't find a bit which contains this information.

My guess for now: the server guesses the battery status by counting packages and reseting the age when the sensor is reset (package ID = 16384).

**Comment by sarnau** [comment]
I a forum somebody mentioned a broken sensor triggered a low-battery message, but I have never seen it so far. The device always just disappears. Still no idea.

**Comment by hfrmobile** [comment]
From my side it looks like that battery status is calculated following way; random multiplied by PI² ...

Adding a new sensor via Android App via scanning QR code (MAC address): "Batterie: GUT" (Battery OK) but I didn't add batteries to the sensor ...

**Comment by sarnau** [comment]
Yes, it is weird. Maybe it was planned at some point or broken in hardware, so that it was never implemented and it is just fake date?

**Comment by sarnau** [comment]
Bit 15 in the Tx word!
