### ISSUE TITLE
TypeError: sensors.setLocale is not a function

### ISSUE THREAD

**Issue by pkolmann** [sarnau/MMMMobileAlerts#41]
I have updated to the latest version and have a locale setting in my config but I have hit this error now:

`MMMMobileAlerts/maserver/mobilealerts.js:212
    sensors.setLocale(locale);
            ^

TypeError: sensors.setLocale is not a function
    at Object.<anonymous> (MMMMobileAlerts/maserver/mobilealerts.js:212:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
`

@GreatSUN I don't know enought JavaScript Modules to fix this issue. Can you take a look please..

I have a Node.js version v16.15.0 running.

Thanks
Philipp

**Comment by GreatSUN** [comment]
Hi and sorry,
I did not properly test this implementation.
As a hot-fix, please go to sensors.js and delete function setLocale
`
function setLocale(localeStrIn) {
    localeStr = localeStrIn;
}
`

and place the following after // Sensor classes:

`
Sensor.prototype.setLocale = function(localeStrIn) {
        localeStr = localeStrIn;
}
` 
I will provide the pull-request tomorrow, of sarnau will not fix it before that.

Sorry,
GreatSUN

**Comment by GreatSUN** [comment]
Pullrequest sent. Should not take long until it is merged @sarnau is usually pretty fast ;-)

Sorry again for the issue generated. This surely has been an issue of being too tired to see what I did :(

**Comment by GreatSUN** [comment]
Merge done, current version should be free of issues. In case you find new ones, please don't hesitate to drop a request.
@pkolmann @sarnau -> could one of you close the issue due to this, please?
